install:
 - cd ..
 - mkdir perl-sources

 - appveyor DownloadFile http://downloads.activestate.com/ActivePerl/releases/5.18.4.1803/ActivePerl-5.18.4.1803-MSWin32-x64-298573.zip -FileName perl-sources\ActivePerl-5.18.4-x64.zip
 - unzip -qq perl-sources\ActivePerl-5.18.4-x64.zip
 - mv ActivePerl-5.18.4.1803-MSWin32-x64-298573 ActivePerl
 - set PATH=C:\projects\ActivePerl\perl\bin;C:\projects\ActivePerl\perl\site\bin;%PATH%
 - C:\projects\ActivePerl\perl\bin\perl perl\bin\reloc_perl -i C:\projects\ActivePerl\perl

cache:
 - C:\projects\perl-sources

build_script:
 - ppm install App-cpanminus Dist-Zilla Pod-Coverage-TrustPod File-ShareDir-Install File-chdir
 - ppm install ExtUtils-Helpers ExtUtils-Config ExtUtils-InstallPaths Module-Build-Tiny
 - ppm install MooseX-Types-Path-Tiny MooseX-Types-Stringlike
 - ppm install IPC-Run IPC-System-Simple Config-Identity Version-Next syntax autobox Sort-Versions
 - ppm install Dist-Zilla-Plugin-MakeMaker-Awesome
 - ppm install IO-CaptureOutput Devel-CheckLib
 - cpanm --notest Dist::Zilla::PluginBundle::Author::ALEXBIO
 - cd p5-Git-Raw
# - perl scripts\bootstrap_windows.pl App::cpanminus
 - dzil listdeps --missing | cpanm --notest
 - dzil test --all
